[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_spl_token = "56EWmgyiEcXFwVu55n49Y8dsunada6pD273XaDRWs1LH"
# anchor_spl_token = "target/deploy/anchor_spl_token.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
